//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleModules.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoogleModules.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed..
        /// </summary>
        internal static string General_AuthenticationFailed {
            get {
                return ResourceManager.GetString("General_AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file doesn&apos;t exist..
        /// </summary>
        internal static string General_FileNotFound {
            get {
                return ResourceManager.GetString("General_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain at least one character..
        /// </summary>
        internal static string General_NoCharacter {
            get {
                return ResourceManager.GetString("General_NoCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authenticated..
        /// </summary>
        internal static string General_NotAuthenticated {
            get {
                return ResourceManager.GetString("General_NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is too long..
        /// </summary>
        internal static string General_TooLong {
            get {
                return ResourceManager.GetString("General_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41016818966.apps.googleusercontent.com.
        /// </summary>
        internal static string Google_ClientID {
            get {
                return ResourceManager.GetString("Google_ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uWqNYTTFmHPj2rd_3VYNctT6.
        /// </summary>
        internal static string Google_ClientSecret {
            get {
                return ResourceManager.GetString("Google_ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the location must contain at least one character..
        /// </summary>
        internal static string GoogleMaps_Location_NoCharacter {
            get {
                return ResourceManager.GetString("GoogleMaps_Location_NoCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the location is too long..
        /// </summary>
        internal static string GoogleMaps_Location_TooLong {
            get {
                return ResourceManager.GetString("GoogleMaps_Location_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Maps: Search Location.
        /// </summary>
        internal static string GoogleMapsSearchLocation_Title {
            get {
                return ResourceManager.GetString("GoogleMapsSearchLocation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyDC9EuY_1hg4V-CjUzuSRWO9K9bpJE5bic.
        /// </summary>
        internal static string GooglePlus_ApiKey {
            get {
                return ResourceManager.GetString("GooglePlus_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization code must contain at least one character..
        /// </summary>
        internal static string GooglePlus_AuthorizationCode_NoCharacter {
            get {
                return ResourceManager.GetString("GooglePlus_AuthorizationCode_NoCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization code  is too long..
        /// </summary>
        internal static string GooglePlus_AuthorizationCode_TooLong {
            get {
                return ResourceManager.GetString("GooglePlus_AuthorizationCode_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The blog entry could not be added to Google+ History.
        /// </summary>
        internal static string GooglePlus_BlogEntryCouldntBeAdded {
            get {
                return ResourceManager.GetString("GooglePlus_BlogEntryCouldntBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The blog entry was succesful added.
        /// </summary>
        internal static string GooglePlus_BlogEntrySuccesfulAdded {
            get {
                return ResourceManager.GetString("GooglePlus_BlogEntrySuccesfulAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Url of the blog entry you want to add to Google+ History..
        /// </summary>
        internal static string GooglePlus_DetailsPostBlogEntry {
            get {
                return ResourceManager.GetString("GooglePlus_DetailsPostBlogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Url of the photo you want to add to Google+ History..
        /// </summary>
        internal static string GooglePlus_DetailsPostPhoto {
            get {
                return ResourceManager.GetString("GooglePlus_DetailsPostPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Url of the video you want to add to Google+ History..
        /// </summary>
        internal static string GooglePlus_DetailsPostVideo {
            get {
                return ResourceManager.GetString("GooglePlus_DetailsPostVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at monitoring the Google+ feed activity..
        /// </summary>
        internal static string GooglePlus_ErrorMonitoringNewActivity {
            get {
                return ResourceManager.GetString("GooglePlus_ErrorMonitoringNewActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at monitoring the Google+ comments..
        /// </summary>
        internal static string GooglePlus_ErrorMonitoringNewComment {
            get {
                return ResourceManager.GetString("GooglePlus_ErrorMonitoringNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event could not be enabled..
        /// </summary>
        internal static string GooglePlus_EventCouldntBeEnabled {
            get {
                return ResourceManager.GetString("GooglePlus_EventCouldntBeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text of the moment must contain at least one character..
        /// </summary>
        internal static string GooglePlus_MomentText_NoCharacter {
            get {
                return ResourceManager.GetString("GooglePlus_MomentText_NoCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text of the moment is too long..
        /// </summary>
        internal static string GooglePlus_MomentText_TooLong {
            get {
                return ResourceManager.GetString("GooglePlus_MomentText_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Entry Url:.
        /// </summary>
        internal static string GooglePlus_PostBlogEntryUrlText {
            get {
                return ResourceManager.GetString("GooglePlus_PostBlogEntryUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Url:.
        /// </summary>
        internal static string GooglePlus_PostPhotoUrlText {
            get {
                return ResourceManager.GetString("GooglePlus_PostPhotoUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Url:.
        /// </summary>
        internal static string GooglePlus_PostVideoUrlText {
            get {
                return ResourceManager.GetString("GooglePlus_PostVideoUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Profile ID must contain at least one character..
        /// </summary>
        internal static string GooglePlus_ProfileID_NoCharacter {
            get {
                return ResourceManager.GetString("GooglePlus_ProfileID_NoCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Profile ID is too long..
        /// </summary>
        internal static string GooglePlus_ProfileID_TooLong {
            get {
                return ResourceManager.GetString("GooglePlus_ProfileID_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Profile ID is incorrect..
        /// </summary>
        internal static string GooglePlus_ProfileIDIncorrect {
            get {
                return ResourceManager.GetString("GooglePlus_ProfileIDIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video could not be added to Google+ History.
        /// </summary>
        internal static string GooglePlus_VideoCouldntBeAdded {
            get {
                return ResourceManager.GetString("GooglePlus_VideoCouldntBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video was succesful added.
        /// </summary>
        internal static string GooglePlus_VideoSuccesfulAdded {
            get {
                return ResourceManager.GetString("GooglePlus_VideoSuccesfulAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google+: New Activity.
        /// </summary>
        internal static string GooglePlusNewActivity_Title {
            get {
                return ResourceManager.GetString("GooglePlusNewActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google+: Receive Comment.
        /// </summary>
        internal static string GooglePlusNewCommentTitle {
            get {
                return ResourceManager.GetString("GooglePlusNewCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google+: Post Blog Entry.
        /// </summary>
        internal static string GooglePlusPostBlogEntry_Title {
            get {
                return ResourceManager.GetString("GooglePlusPostBlogEntry_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google+: Post Photo.
        /// </summary>
        internal static string GooglePlusPostPhoto_Title {
            get {
                return ResourceManager.GetString("GooglePlusPostPhoto_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google+: Post Video.
        /// </summary>
        internal static string GooglePlusPostVideo_Title {
            get {
                return ResourceManager.GetString("GooglePlusPostVideo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: {0}. Map type: {1}..
        /// </summary>
        internal static string LocationMapType_ConfigString {
            get {
                return ResourceManager.GetString("LocationMapType_ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moment Url: {0}..
        /// </summary>
        internal static string MomentUrl_ConfigString {
            get {
                return ResourceManager.GetString("MomentUrl_ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile ID: {0}..
        /// </summary>
        internal static string ProfileID_ConfigString {
            get {
                return ResourceManager.GetString("ProfileID_ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video title: {0}..
        /// </summary>
        internal static string UploadVideo_ConfigString {
            get {
                return ResourceManager.GetString("UploadVideo_ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string YouTube_Category {
            get {
                return ResourceManager.GetString("YouTube_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string YouTube_Description {
            get {
                return ResourceManager.GetString("YouTube_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI39si4VuUApLd4VGVwxWEwKMwbNs1dhSeVEc1LGavmXEwnP1QsUq9FHL81tTdDq4_bQRf0SSP6VvvVovht6Xioy3l-9v2awOw.
        /// </summary>
        internal static string YouTube_DeveloperKey {
            get {
                return ResourceManager.GetString("YouTube_DeveloperKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string YouTube_Keywords {
            get {
                return ResourceManager.GetString("YouTube_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string YouTube_Password {
            get {
                return ResourceManager.GetString("YouTube_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayhem.
        /// </summary>
        internal static string YouTube_ProductName {
            get {
                return ResourceManager.GetString("YouTube_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video &apos;{0}&apos; could not be uploaded..
        /// </summary>
        internal static string YouTube_UploadFailed {
            get {
                return ResourceManager.GetString("YouTube_UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video &apos;{0}&apos; was successfully uploaded..
        /// </summary>
        internal static string YouTube_UploadSuccesful {
            get {
                return ResourceManager.GetString("YouTube_UploadSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string YouTube_Username {
            get {
                return ResourceManager.GetString("YouTube_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path of the video.
        /// </summary>
        internal static string YouTube_VideoPath {
            get {
                return ResourceManager.GetString("YouTube_VideoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Title.
        /// </summary>
        internal static string YouTube_VideoTitle {
            get {
                return ResourceManager.GetString("YouTube_VideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube: Upload Video.
        /// </summary>
        internal static string YouTubeUploadVideo_Title {
            get {
                return ResourceManager.GetString("YouTubeUploadVideo_Title", resourceCulture);
            }
        }
    }
}
