//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeModules.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeModules.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel application not found..
        /// </summary>
        internal static string Excel_ApplicationNotFound {
            get {
                return ResourceManager.GetString("Excel_ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check compatibility..
        /// </summary>
        internal static string Excel_CantCheckCompatibility {
            get {
                return ResourceManager.GetString("Excel_CantCheckCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The charts from the current workbook could not be saved..
        /// </summary>
        internal static string Excel_CantSaveCharts {
            get {
                return ResourceManager.GetString("Excel_CantSaveCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No workbook is currently active..
        /// </summary>
        internal static string Excel_NoActiveWorkbook {
            get {
                return ResourceManager.GetString("Excel_NoActiveWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file can&apos;t be opened..
        /// </summary>
        internal static string General_CantOpenFile {
            get {
                return ResourceManager.GetString("General_CantOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory doesn&apos;t exist..
        /// </summary>
        internal static string General_DirectoryNotFound {
            get {
                return ResourceManager.GetString("General_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory: {0}..
        /// </summary>
        internal static string General_DirectorySaveConfigString {
            get {
                return ResourceManager.GetString("General_DirectorySaveConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path must reference a .txt file..
        /// </summary>
        internal static string General_FileFormatNotValid {
            get {
                return ResourceManager.GetString("General_FileFormatNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File location is invalid.
        /// </summary>
        internal static string General_FileLocationInvalid {
            get {
                return ResourceManager.GetString("General_FileLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file doesn&apos;t exist..
        /// </summary>
        internal static string General_FileNotFound {
            get {
                return ResourceManager.GetString("General_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lync application not found..
        /// </summary>
        internal static string Lync_ApplicationNotFound {
            get {
                return ResourceManager.GetString("Lync_ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combo box can&apos;t be empty..
        /// </summary>
        internal static string Lync_ComboBoxNoItems {
            get {
                return ResourceManager.GetString("Lync_ComboBoxNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Id is invalid..
        /// </summary>
        internal static string Lync_InvalidUserId {
            get {
                return ResourceManager.GetString("Lync_InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user is currently logged in..
        /// </summary>
        internal static string Lync_NotLoggedIn {
            get {
                return ResourceManager.GetString("Lync_NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contact with the selected user id exists in your groups..
        /// </summary>
        internal static string Lync_NoUserId {
            get {
                return ResourceManager.GetString("Lync_NoUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lync reaction could not be performed..
        /// </summary>
        internal static string Lync_ReactionCouldntPerform {
            get {
                return ResourceManager.GetString("Lync_ReactionCouldntPerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id: {0}..
        /// </summary>
        internal static string Lync_SelectUserConfigString {
            get {
                return ResourceManager.GetString("Lync_SelectUserConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id: {0}, Status: {1}.
        /// </summary>
        internal static string Lync_StatusChangedConfigString {
            get {
                return ResourceManager.GetString("Lync_StatusChangedConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: {0}..
        /// </summary>
        internal static string Lync_UpdateLocationConfigString {
            get {
                return ResourceManager.GetString("Lync_UpdateLocationConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal note: {0}..
        /// </summary>
        internal static string Lync_UpdatePersonalNoteConfigString {
            get {
                return ResourceManager.GetString("Lync_UpdatePersonalNoteConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}..
        /// </summary>
        internal static string Lync_UpdateStatusConfigString {
            get {
                return ResourceManager.GetString("Lync_UpdateStatusConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook application not found..
        /// </summary>
        internal static string Outlook_ApplicationNotFound {
            get {
                return ResourceManager.GetString("Outlook_ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint application not found..
        /// </summary>
        internal static string PowerPoint_ApplicationNotFound {
            get {
                return ResourceManager.GetString("PowerPoint_ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t go to the first slide..
        /// </summary>
        internal static string PowerPoint_CantChangeSlidesFirst {
            get {
                return ResourceManager.GetString("PowerPoint_CantChangeSlidesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t go to the last slide..
        /// </summary>
        internal static string PowerPoint_CantChangeSlidesLast {
            get {
                return ResourceManager.GetString("PowerPoint_CantChangeSlidesLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t go to the next slide..
        /// </summary>
        internal static string PowerPoint_CantChangeSlidesNext {
            get {
                return ResourceManager.GetString("PowerPoint_CantChangeSlidesNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t go to the previous slide..
        /// </summary>
        internal static string PowerPoint_CantChangeSlidesPrevious {
            get {
                return ResourceManager.GetString("PowerPoint_CantChangeSlidesPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to close the active presentation..
        /// </summary>
        internal static string PowerPoint_CantClosePresentation {
            get {
                return ResourceManager.GetString("PowerPoint_CantClosePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to close the slideshow..
        /// </summary>
        internal static string PowerPoint_CantCloseSideShow {
            get {
                return ResourceManager.GetString("PowerPoint_CantCloseSideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be created..
        /// </summary>
        internal static string PowerPoint_CantCreateFile {
            get {
                return ResourceManager.GetString("PowerPoint_CantCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t close the presentation..
        /// </summary>
        internal static string PowerPoint_CantExitPresentation {
            get {
                return ResourceManager.GetString("PowerPoint_CantExitPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t close the slideshow..
        /// </summary>
        internal static string PowerPoint_CantExitSlideShow {
            get {
                return ResourceManager.GetString("PowerPoint_CantExitSlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t export the notes of the slides..
        /// </summary>
        internal static string PowerPoint_CantExportNotes {
            get {
                return ResourceManager.GetString("PowerPoint_CantExportNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t export the text from the slides..
        /// </summary>
        internal static string PowerPoint_CantExportText {
            get {
                return ResourceManager.GetString("PowerPoint_CantExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pictures from the current slide could not be saved..
        /// </summary>
        internal static string PowerPoint_CantSavePictures {
            get {
                return ResourceManager.GetString("PowerPoint_CantSavePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slideshow can&apos;t be started..
        /// </summary>
        internal static string PowerPoint_CantStartSlideShow {
            get {
                return ResourceManager.GetString("PowerPoint_CantStartSlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path: {0}..
        /// </summary>
        internal static string PowerPoint_ExportConfigString {
            get {
                return ResourceManager.GetString("PowerPoint_ExportConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one slideshow window detected, using the last opened one..
        /// </summary>
        internal static string PowerPoint_MoreThanOneWindow {
            get {
                return ResourceManager.GetString("PowerPoint_MoreThanOneWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An active presentation doesn&apos;t exists..
        /// </summary>
        internal static string PowerPoint_NoActivePresentation {
            get {
                return ResourceManager.GetString("PowerPoint_NoActivePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file is selected..
        /// </summary>
        internal static string PowerPoint_NoFileSelected {
            get {
                return ResourceManager.GetString("PowerPoint_NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected presentation doesn&apos;t have notes..
        /// </summary>
        internal static string PowerPoint_NoNotes {
            get {
                return ResourceManager.GetString("PowerPoint_NoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No slide is currently selected..
        /// </summary>
        internal static string PowerPoint_NoSlideSelected {
            get {
                return ResourceManager.GetString("PowerPoint_NoSlideSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be in a slideshow view to save pictures..
        /// </summary>
        internal static string PowerPoint_NoSlideShowWindow {
            get {
                return ResourceManager.GetString("PowerPoint_NoSlideShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected presentation doesn&apos;t contain text..
        /// </summary>
        internal static string PowerPoint_NoText {
            get {
                return ResourceManager.GetString("PowerPoint_NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be in a slideshow view to change slide..
        /// </summary>
        internal static string PowerPoint_NoWindowCantChange {
            get {
                return ResourceManager.GetString("PowerPoint_NoWindowCantChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the opened Word application..
        /// </summary>
        internal static string Word_ApplicationNotFound {
            get {
                return ResourceManager.GetString("Word_ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t activate the spell checking..
        /// </summary>
        internal static string Word_CantActivateSpellChecking {
            get {
                return ResourceManager.GetString("Word_CantActivateSpellChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pictures from the current document could not be saved..
        /// </summary>
        internal static string Word_CantSavePictures {
            get {
                return ResourceManager.GetString("Word_CantSavePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document is currently active..
        /// </summary>
        internal static string Word_NoActiveDocument {
            get {
                return ResourceManager.GetString("Word_NoActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pictures found in the current document..
        /// </summary>
        internal static string Word_NoPicturesInDocument {
            get {
                return ResourceManager.GetString("Word_NoPicturesInDocument", resourceCulture);
            }
        }
    }
}
