//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectivityModule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConnectivityModule.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the specified device..
        /// </summary>
        internal static string BT_CantConnectToDevice {
            get {
                return ResourceManager.GetString("BT_CantConnectToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t pair with the predefined device..
        /// </summary>
        internal static string BT_CantPairWithDevice {
            get {
                return ResourceManager.GetString("BT_CantPairWithDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection refused by peer..
        /// </summary>
        internal static string BT_ConnectionRefused {
            get {
                return ResourceManager.GetString("BT_ConnectionRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the device must be 17 characters long or smaller..
        /// </summary>
        internal static string BT_DeviceAddress_TooLong {
            get {
                return ResourceManager.GetString("BT_DeviceAddress_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address of the device must be at least 12 characters long..
        /// </summary>
        internal static string BT_DeviceAddress_TooShort {
            get {
                return ResourceManager.GetString("BT_DeviceAddress_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device with the address {0} is not visible..
        /// </summary>
        internal static string BT_DeviceAddressNotFound {
            get {
                return ResourceManager.GetString("BT_DeviceAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the device must contain at least one character..
        /// </summary>
        internal static string BT_DeviceName_NoCharacter {
            get {
                return ResourceManager.GetString("BT_DeviceName_NoCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the device must be 100 characters long or smaller..
        /// </summary>
        internal static string BT_DeviceName_TooLong {
            get {
                return ResourceManager.GetString("BT_DeviceName_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device {0} is not visible..
        /// </summary>
        internal static string BT_DeviceNotFound {
            get {
                return ResourceManager.GetString("BT_DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device is already not visible..
        /// </summary>
        internal static string BT_DeviceNotVisible {
            get {
                return ResourceManager.GetString("BT_DeviceNotVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device is already visible..
        /// </summary>
        internal static string BT_DeviceVisible {
            get {
                return ResourceManager.GetString("BT_DeviceVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at monitoring the bluetooth activity..
        /// </summary>
        internal static string BT_ErrorMonitoringBluetooth {
            get {
                return ResourceManager.GetString("BT_ErrorMonitoringBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Becomes visible..
        /// </summary>
        internal static string BT_MonitorBecomesVisible {
            get {
                return ResourceManager.GetString("BT_MonitorBecomesVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No longer visible..
        /// </summary>
        internal static string BT_MonitorNoLongerVisible {
            get {
                return ResourceManager.GetString("BT_MonitorNoLongerVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Bluetooth found..
        /// </summary>
        internal static string BT_NoBluetooth {
            get {
                return ResourceManager.GetString("BT_NoBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pin must contain at least one character..
        /// </summary>
        internal static string BT_Pin_NoCharacter {
            get {
                return ResourceManager.GetString("BT_Pin_NoCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pin is too long..
        /// </summary>
        internal static string BT_Pin_TooLong {
            get {
                return ResourceManager.GetString("BT_Pin_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time interval must be greater than 5 seconds..
        /// </summary>
        internal static string BT_SecondsMoreThan5 {
            get {
                return ResourceManager.GetString("BT_SecondsMoreThan5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device with the name {0} was succesful paired with the computer..
        /// </summary>
        internal static string BT_SuccessfulPair {
            get {
                return ResourceManager.GetString("BT_SuccessfulPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device with the address {0} was succesful paired with the computer..
        /// </summary>
        internal static string BT_SuccessfulPairAddress {
            get {
                return ResourceManager.GetString("BT_SuccessfulPairAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device&apos;s address: {0}..
        /// </summary>
        internal static string DeviceAddress_ConfigString {
            get {
                return ResourceManager.GetString("DeviceAddress_ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device&apos;s name: {0}. Monitor: {1}..
        /// </summary>
        internal static string DeviceName_ConfigString {
            get {
                return ResourceManager.GetString("DeviceName_ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor device.
        /// </summary>
        internal static string DeviceName_Title {
            get {
                return ResourceManager.GetString("DeviceName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor device becomes visible.
        /// </summary>
        internal static string DeviceNameBecomes_Title {
            get {
                return ResourceManager.GetString("DeviceNameBecomes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to device.
        /// </summary>
        internal static string DeviceNameConnect_Title {
            get {
                return ResourceManager.GetString("DeviceNameConnect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device&apos;s address: {0}. Pin {1}..
        /// </summary>
        internal static string DevicePairAddress_ConfigString {
            get {
                return ResourceManager.GetString("DevicePairAddress_ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device&apos;s name: {0}. Pin {1}..
        /// </summary>
        internal static string DevicePairName_ConfigString {
            get {
                return ResourceManager.GetString("DevicePairName_ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string General_BluetoothTimerInterval {
            get {
                return ResourceManager.GetString("General_BluetoothTimerInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File location is invalid..
        /// </summary>
        internal static string General_FileLocationInvalid {
            get {
                return ResourceManager.GetString("General_FileLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string General_FileNotFound {
            get {
                return ResourceManager.GetString("General_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        internal static string General_TimerInterval {
            get {
                return ResourceManager.GetString("General_TimerInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network&apos;s name: {0}..
        /// </summary>
        internal static string NetworkName_ConfigString {
            get {
                return ResourceManager.GetString("NetworkName_ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor network.
        /// </summary>
        internal static string NetworkName_Title {
            get {
                return ResourceManager.GetString("NetworkName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair with device.
        /// </summary>
        internal static string PairWithDevice_Title {
            get {
                return ResourceManager.GetString("PairWithDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send file to device.
        /// </summary>
        internal static string SendFileToDevice_Title {
            get {
                return ResourceManager.GetString("SendFileToDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succes.
        /// </summary>
        internal static string Succes {
            get {
                return ResourceManager.GetString("Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the selected network..
        /// </summary>
        internal static string WiFi_CantConnectToNetwork {
            get {
                return ResourceManager.GetString("WiFi_CantConnectToNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t disconnect from the selected network..
        /// </summary>
        internal static string WiFi_CantDisconnectFromNetwork {
            get {
                return ResourceManager.GetString("WiFi_CantDisconnectFromNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get the available networks..
        /// </summary>
        internal static string WiFi_CantGetNetworks {
            get {
                return ResourceManager.GetString("WiFi_CantGetNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from the {0} network..
        /// </summary>
        internal static string WiFi_DisconnectedFromNetwork {
            get {
                return ResourceManager.GetString("WiFi_DisconnectedFromNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network {0} is already not visible..
        /// </summary>
        internal static string WiFi_NetworkAlreadyNotVisible {
            get {
                return ResourceManager.GetString("WiFi_NetworkAlreadyNotVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network {0} is already visible..
        /// </summary>
        internal static string WiFi_NetworkAlreadyVisible {
            get {
                return ResourceManager.GetString("WiFi_NetworkAlreadyVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the network must contain at least one character..
        /// </summary>
        internal static string WiFi_NetworkName_NoCharacter {
            get {
                return ResourceManager.GetString("WiFi_NetworkName_NoCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the network must be 100 characters long or smaller..
        /// </summary>
        internal static string WiFi_NetworkName_TooLong {
            get {
                return ResourceManager.GetString("WiFi_NetworkName_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network {0} is not visible..
        /// </summary>
        internal static string WiFi_NetworkNotVisible {
            get {
                return ResourceManager.GetString("WiFi_NetworkNotVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computer is not connected to the {0} network..
        /// </summary>
        internal static string WiFi_NoNetworkConnected {
            get {
                return ResourceManager.GetString("WiFi_NoNetworkConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Wi-Fi networks found..
        /// </summary>
        internal static string WiFi_NoNetworks {
            get {
                return ResourceManager.GetString("WiFi_NoNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of seconds can&apos;t be 0..
        /// </summary>
        internal static string WiFi_Seconds_GreaterThanZero {
            get {
                return ResourceManager.GetString("WiFi_Seconds_GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of seconds is invalid..
        /// </summary>
        internal static string WiFi_Seconds_Invalid {
            get {
                return ResourceManager.GetString("WiFi_Seconds_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection to the {0} network was successfully established..
        /// </summary>
        internal static string WiFi_SuccessConnectedNetwork {
            get {
                return ResourceManager.GetString("WiFi_SuccessConnectedNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wi-Fi capability is not enabled..
        /// </summary>
        internal static string WiFi_WiFiNotAvailable {
            get {
                return ResourceManager.GetString("WiFi_WiFiNotAvailable", resourceCulture);
            }
        }
    }
}
