//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeModules.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkypeModules.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype: Call Contact.
        /// </summary>
        internal static string CallContact_Title {
            get {
                return ResourceManager.GetString("CallContact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype: Call Ended.
        /// </summary>
        internal static string CallEnded_Title {
            get {
                return ResourceManager.GetString("CallEnded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype: Change Status.
        /// </summary>
        internal static string ChangeStatus_Title {
            get {
                return ResourceManager.GetString("ChangeStatus_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to the &apos;{0}&apos; contact can&apos;t be put on hold..
        /// </summary>
        internal static string Error_CallCantPutOnHold {
            get {
                return ResourceManager.GetString("Error_CallCantPutOnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to the &apos;{0}&apos; contact can&apos;t be resumed..
        /// </summary>
        internal static string Error_CallCantResume {
            get {
                return ResourceManager.GetString("Error_CallCantResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call to the &apos;{0}&apos; contact couldn&apos;t be established..
        /// </summary>
        internal static string Error_CallingContact {
            get {
                return ResourceManager.GetString("Error_CallingContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active call exists between you and &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CallNotActive {
            get {
                return ResourceManager.GetString("Error_CallNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No call in progress exists between you and &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CallNotInProgress {
            get {
                return ResourceManager.GetString("Error_CallNotInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No call on hold exists between you and &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CallNotOnHold {
            get {
                return ResourceManager.GetString("Error_CallNotOnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current status can&apos;t be changed..
        /// </summary>
        internal static string Error_CantChangeStatus {
            get {
                return ResourceManager.GetString("Error_CantChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t mute/unmute the microphone..
        /// </summary>
        internal static string Error_CantMuteUnmute {
            get {
                return ResourceManager.GetString("Error_CantMuteUnmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t mute/unmute the microphone because an active call doesn&apos;t exist..
        /// </summary>
        internal static string Error_CantMuteUnmuteNoCall {
            get {
                return ResourceManager.GetString("Error_CantMuteUnmuteNoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at connecting with Skype..
        /// </summary>
        internal static string Error_ConnectingSkype {
            get {
                return ResourceManager.GetString("Error_ConnectingSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact &apos;{0}&apos; was not found in your contact list..
        /// </summary>
        internal static string Error_ContactNotFound {
            get {
                return ResourceManager.GetString("Error_ContactNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event &apos;{0}&apos; couldn&apos;t be triggered..
        /// </summary>
        internal static string Error_EventCantBeTriggered {
            get {
                return ResourceManager.GetString("Error_EventCantBeTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected audio message can&apos;t be sent to &apos;{0}&apos;..
        /// </summary>
        internal static string Error_SendingAudioMessage {
            get {
                return ResourceManager.GetString("Error_SendingAudioMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected message can&apos;t be sent to &apos;{0}&apos;..
        /// </summary>
        internal static string Error_SendingChatMessage {
            get {
                return ResourceManager.GetString("Error_SendingChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file path.
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must have the .wav extension..
        /// </summary>
        internal static string General_FileFormatNotValid {
            get {
                return ResourceManager.GetString("General_FileFormatNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file doesn&apos;t exist..
        /// </summary>
        internal static string General_FileNotFound {
            get {
                return ResourceManager.GetString("General_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must contain at least one character..
        /// </summary>
        internal static string General_NoCharacter {
            get {
                return ResourceManager.GetString("General_NoCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is too long..
        /// </summary>
        internal static string General_TooLong {
            get {
                return ResourceManager.GetString("General_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype: Hold Call.
        /// </summary>
        internal static string HoldCall_Title {
            get {
                return ResourceManager.GetString("HoldCall_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype: Call Holded.
        /// </summary>
        internal static string OnHoldCall_Title {
            get {
                return ResourceManager.GetString("OnHoldCall_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype: Receive Call.
        /// </summary>
        internal static string ReceiveCall_Title {
            get {
                return ResourceManager.GetString("ReceiveCall_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype: Chat Message Received.
        /// </summary>
        internal static string ReceiveChatMessage_Title {
            get {
                return ResourceManager.GetString("ReceiveChatMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype: Receive SMS.
        /// </summary>
        internal static string ReceiveSms_Title {
            get {
                return ResourceManager.GetString("ReceiveSms_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype: Play Audio Message.
        /// </summary>
        internal static string SendAudioMessage_Title {
            get {
                return ResourceManager.GetString("SendAudioMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype: Send Chat Message.
        /// </summary>
        internal static string SendMessage_Title {
            get {
                return ResourceManager.GetString("SendMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype ID: {0}. File path: {1}..
        /// </summary>
        internal static string SkypeAudioMessage_ConfigString {
            get {
                return ResourceManager.GetString("SkypeAudioMessage_ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype ID.
        /// </summary>
        internal static string SkypeID {
            get {
                return ResourceManager.GetString("SkypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype ID: {0}..
        /// </summary>
        internal static string SkypeID_ConfigString {
            get {
                return ResourceManager.GetString("SkypeID_ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype ID: {0}. Message: {1}..
        /// </summary>
        internal static string SkypeMessage_ConfigString {
            get {
                return ResourceManager.GetString("SkypeMessage_ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}..
        /// </summary>
        internal static string Status_ConfigString {
            get {
                return ResourceManager.GetString("Status_ConfigString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audio message was succesful sent..
        /// </summary>
        internal static string Successful_AudioMessage {
            get {
                return ResourceManager.GetString("Successful_AudioMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chat message was succesful sent..
        /// </summary>
        internal static string Successful_ChatMessage {
            get {
                return ResourceManager.GetString("Successful_ChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype: Unhold Call.
        /// </summary>
        internal static string UnholdCall_Title {
            get {
                return ResourceManager.GetString("UnholdCall_Title", resourceCulture);
            }
        }
    }
}
